# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cancan_namespace 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "cancan_namespace"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = "2016-04-11"
  s.description = "Add namespace for cancan authorization library"
  s.email = "galeta.igor@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/cancan_namespace.rb",
    "lib/cancan_namespace/ability.rb",
    "lib/cancan_namespace/controller_additions.rb",
    "lib/cancan_namespace/controller_resource.rb",
    "lib/cancan_namespace/model_adapters/active_record_adapter.rb",
    "lib/cancan_namespace/model_additions.rb",
    "lib/cancan_namespace/rule.rb",
    "lib/cancan_namespace/version.rb"
  ]
  s.homepage = "https://github.com/galetahub/cancan_namespace"
  s.rubyforge_project = "cancan_namespace"
  s.rubygems_version = "2.4.8"
  s.summary = "Cancan namespace"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cancancan>, [">= 1.13.1"])
    else
      s.add_dependency(%q<cancancan>, [">= 1.13.1"])
    end
  else
    s.add_dependency(%q<cancancan>, [">= 1.13.1"])
  end
end

